# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASoC_Stage'
    applications: '8994d026-1dd5-4642-9c0e-ec775ae97e66'
    scanname: 'TFS-205_MAST'
    scantype: 'mobile'
    appFile: 'C:\Test data\demo.apk'
