# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: TFS_206_Agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASoC_Mirror'
    applications: 'cc802ac1-9a1b-42c4-971c-74f774e035c5'
    scanname: 'DAST_YAML_205'
    scantype: 'dynamic'
    dynamicType: 'DAST'
    scanURL: 'http://demo.testfire.net/'
    type: 'production'
    loginMethod: 'None'
    network: 'public'
    optimization: 'fastest'


- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASoC_Mirror'
    applications: 'cc802ac1-9a1b-42c4-971c-74f774e035c5'
    scanname: 'SAST_YAML_205'
    scantype: 'static'
    scanloc: 'Altoro_WAR'
    ScanSpeedOptions: 'simple'
