# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: Security_Test
    jobs:
      - job: execSecurityTest
        pool:
          name: TFS_206_Agent

        steps:
        - task: HCLAppScanOnCloud@2
          inputs:
            AppSecTestService: 'ASoC_Prod'
            applications: '92abe340-b3cd-4267-afa2-6e9f1e0b49dd'
            scanname: 'DTF_Rel_Pip'
            scantype: 'dynamic'
            scanURL: 'http://demo.testfire.net?mode=demo'
            dynamicType: 'DAST'
            type: 'production'
            loginMethod: 'None'
            network: 'public'
            optimization: 'fastest'
            

