# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: Security_Test
    jobs:
      - job: execSecurityTest
        pool:
          name: TFS_206_Agent

        steps:
        - task: HCLAppScanPluginsQA.ApplicationSecurity-VSTS.custom-asoc-task.HCLAppScanOnCloud@2
        displayName: 'Run HCL AppScan on Cloud Security Test'
        inputs:
          AppSecTestService: 'ASoC_Stage'
          applications: '8994d026-1dd5-4642-9c0e-ec775ae97e66'
          scanname: 'DAST_201'
          scantype: dynamic
          scanURL: 'http://demo.testfire.net'
          OpenSourceScanOnly: false
          ScanSpeedOptions: simple
          type: production
          optimization: fastest
            

