# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: TFS_206_Agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: HCLTechnologies.ApplicationSecurity-VSTS.custom-asoc-task.HCLAppScanOnCloud@2
  displayName: 'Run HCL AppScan on Cloud Security Test'
  inputs:
    AppSecTestService: 'ASoC_Stage'
    applications: '8994d026-1dd5-4642-9c0e-ec775ae97e66'
    scanname: 'OSS_TFS_206_YAML'
    scanloc: 'Altoro_WAR'
    OpenSourceScanOnly: true
    ScanSpeedOptions: simple


- task: HCLTechnologies.ApplicationSecurity-VSTS.custom-ase-task.HCL AppScan Enterprise@2
  displayName: 'Run HCL AppScan Enterprise Security Test'
  inputs:
    ServiceEndPointAse: 'ASE_227'
    jobName: 'TFS_ASE_206_YAML'
    folderId: 4
    templateId: 13
    testPolicyId: 8
    applicationId: 74
    startingURL: 'http://10.115.153.71:18080/WebGoat/login'
    loginMethod: None
    optimization: Fastest
